# coding: utf-8

"""
    Program Administration API

    The Transaction Controls Program Administration API enables Issuers to change program configurations for their sponsorID.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import sys
from setuptools import setup, find_packages

NAME = "src"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Program Administration API",
    author_email="",
    url="",
    keywords=["Swagger", "Program Administration API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    The Transaction Controls Program Administration API enables Issuers to change program configurations for their sponsorID.
    """
)
