# Generated by Django 3.0.5 on 2020-05-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.TextField(unique=True)),
                ('accountName', models.TextField()),
                ('accountType', models.CharField(max_length=30)),
                ('extraData', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.TextField(unique=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('name', models.TextField()),
                ('extra_data', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('personGroup', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.PersonGroup')),
            ],
        ),
        migrations.CreateModel(
            name='BankCred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=30)),
                ('code', models.TextField(unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Person')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.BankCred'),
        ),
    ]
