# Generated by Django 3.0.5 on 2020-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcred',
            name='username',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='bankcred',
            name='userpass',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='bankcred',
            name='code',
            field=models.TextField(),
        ),
    ]
