# Generated by Django 3.0.5 on 2020-05-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20200520_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='persongroup',
            name='lastUpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionId',
            field=models.TextField(),
        ),
    ]
