# Generated by Django 3.0.5 on 2020-05-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20200520_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcred',
            old_name='code',
            new_name='plaidCode',
        ),
    ]
