# Generated by Django 3.0.5 on 2020-05-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_bankcred_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='token',
            field=models.TextField(default='GU2wb2YOboJF6V9B'),
            preserve_default=False,
        ),
    ]
