# Generated by Django 3.0.5 on 2020-06-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20200623_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='restricted',
        ),
        migrations.AddField(
            model_name='account',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
