# Generated by Django 3.0.5 on 2020-06-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20200623_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='extraData',
        ),
    ]
