# Generated by Django 3.0.5 on 2020-06-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
