# Generated by Django 3.0.5 on 2020-06-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_auto_20200628_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.FloatField(default=12.34),
            preserve_default=False,
        ),
    ]
