# Generated by Django 3.0.5 on 2020-07-28 23:48

from django.db import migrations, models
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_receipt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=smartfields.fields.ImageField(upload_to=''),
        ),
    ]
