# Generated by Django 3.0.5 on 2020-08-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_auto_20200730_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='name',
        ),
        migrations.AddField(
            model_name='receipt',
            name='memo',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='purchasedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='store',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
