# Generated by Django 3.0.5 on 2024-03-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0004_auto_20240306_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodvendor',
            name='FirePreventionDistricts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodvendor',
            name='PoliceDistricts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodvendor',
            name='SupervisorDistricts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodvendor',
            name='X',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='foodvendor',
            name='Y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='foodvendor',
            name='ZipCodes',
            field=models.IntegerField(null=True),
        ),
    ]
