# Generated by Django 3.0.5 on 2024-03-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0005_auto_20240306_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodvendor',
            name='FirePreventionDistricts',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='NOISent',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='Neighborhoods',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='PoliceDistricts',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='Schedule',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='SupervisorDistricts',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='X',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='Y',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='block',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='blocklot',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='lot',
        ),
    ]
