# Generated by Django 3.0.5 on 2024-03-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0006_auto_20240308_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='Applicant',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='Approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='dayshours',
            new_name='days_hours',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='ExpirationDate',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='FacilityType',
            new_name='facility_type',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='FoodItems',
            new_name='food_items',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='LocationDescription',
            new_name='location_description',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='cnn',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='PriorPermit',
            new_name='prior_permit',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='Received',
            new_name='received',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='foodvendor',
            old_name='ZipCodes',
            new_name='zip_codes',
        ),
        migrations.RemoveField(
            model_name='foodvendor',
            name='locationid',
        ),
    ]
