# coding: utf-8

"""
    Program Administration API

    The Transaction Controls Program Administration API enables Issuers to change program configurations for their sponsorID.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest
import datetime
import pytz
import random
import string
import re
import json

from src.apis.prog_admin_api import ProgAdminApi
from src.configuration import Configuration
from globalConfig import GlobalConfig


class TestProgAdminApi(unittest.TestCase):
    """ ProgAdminApi unit test stubs """

    @classmethod
    def setUpClass(self):
        print("---------------------------------------Tests---------------------------------------\nProduct Name: Visa Transaction Controls\nApi Name: Program Administration API")
        globalConfig = GlobalConfig()
        config = Configuration()
        config.username = globalConfig.userName
        config.password = globalConfig.password
        config.cert_file = globalConfig.certificatePath
        config.key_file = globalConfig.privateKeyPath
        config.shared_secret = globalConfig.sharedSecret
        config.api_key['apikey'] = globalConfig.apiKey
        config.ssl_ca_cert = globalConfig.caCertPath
        config.proxy_url = globalConfig.proxyUrl
        self.api = ProgAdminApi(None)

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def transformPayload(self, payload):
        payload = self.editLocalTime(payload)
        payload = self.addRandom(payload)
        payload = json.loads(payload)
        return payload

    def editLocalTime(self, payload):
        timezone = pytz.timezone("America/Los_Angeles")
        timestamp = timezone.localize(datetime.datetime.now()).strftime('%Y-%m-%dT%H:%M:%S')
        pattern = re.compile('"localTransactionDateTime":".{19}"', re.IGNORECASE)
        replacement = '"localTransactionDateTime": "'+timestamp+'"'
        payload = re.sub(pattern, replacement, payload)

        timestamp = timezone.localize(datetime.datetime.now()).strftime('%m%d%H%M%S')
        pattern = re.compile('"dateTimeLocal":".{10}"', re.IGNORECASE)
        replacement = '"dateTimeLocal": "'+timestamp+'"'
        payload = re.sub(pattern, replacement, payload)
        return payload

    def addRandom(self, payload):
        if payload == 'mle_keyId':
            return self.mleKeyId
        payload = re.sub(r'random_string', ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(8)), payload)
        payload = re.sub(r'random_integer', ''.join(random.choice(string.digits) for _ in range(8)), payload)
        payload= re.sub(r'random', ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(8)), payload)
        return payload

    """
    Test case for deletemanage_rule_configuration

    .
    """
    def testdeletemanage_rule_configuration(self):
        print("\ndeletemanage_rule_configuration")
        result = self.api.deletemanage_rule_configuration(self.transformPayload('{"ruleCategories":["PCT_MERCHANT"]}'))
        pass

    """
    Test case for deletemanage_transaction_controls

    .
    """
    def testdeletemanage_transaction_controls(self):
        print("\ndeletemanage_transaction_controls")
        result = self.api.deletemanage_transaction_controls(self.transformPayload('{"transactionTypeRules":["TCT_ATM_WITHDRAW"]}'))
        pass

    """
    Test case for getmanage_rule_configuration

    .
    """
    def testgetmanage_rule_configuration(self):
        print("\ngetmanage_rule_configuration")
        result = self.api.getmanage_rule_configuration()
        pass

    """
    Test case for getmanage_transaction_controls

    .
    """
    def testgetmanage_transaction_controls(self):
        print("\ngetmanage_transaction_controls")
        result = self.api.getmanage_transaction_controls()
        pass

    """
    Test case for postmanage_rule_configuration

    .
    """
    def testpostmanage_rule_configuration(self):
        print("\npostmanage_rule_configuration")
        result = self.api.postmanage_rule_configuration(self.transformPayload('{"ruleCategories":["PCT_MERCHANT"]}'))
        pass

    """
    Test case for postmanage_transaction_controls

    .
    """
    def testpostmanage_transaction_controls(self):
        print("\npostmanage_transaction_controls")
        result = self.api.postmanage_transaction_controls(self.transformPayload('{"transactionTypeRules":["TCT_ATM_WITHDRAW"]}'))
        pass

    """
    Test case for putmanage_rule_configuration

    .
    """
    def testputmanage_rule_configuration(self):
        print("\nputmanage_rule_configuration")
        result = self.api.putmanage_rule_configuration(self.transformPayload('{"ruleCategories":["PCT_MERCHANT"]}'))
        pass

    """
    Test case for putmanage_transaction_controls

    .
    """
    def testputmanage_transaction_controls(self):
        print("\nputmanage_transaction_controls")
        result = self.api.putmanage_transaction_controls(self.transformPayload('{"transactionTypeRules":["TCT_ATM_WITHDRAW"]}'))
        pass


if __name__ == '__main__':
    unittest.main()


# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------