# coding: utf-8

"""
    Customer Rules API

    The Customer Rules API enables consumers to establish control rules that will define the type of transactions they want to Manage.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class BatchEnrollmentpostPayload(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, control_rules=None, cards_type=None, force_enrollment=None, enrolled_cards=None):
        """
        BatchEnrollmentpostPayload - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'control_rules': 'ControlRules',
            'cards_type': 'str',
            'force_enrollment': 'bool',
            'enrolled_cards': 'EnrolledCards'
        }

        self.attribute_map = {
            'control_rules': 'controlRules',
            'cards_type': 'cardsType',
            'force_enrollment': 'forceEnrollment',
            'enrolled_cards': 'enrolledCards'
        }

        self._control_rules = control_rules
        self._cards_type = cards_type
        self._force_enrollment = force_enrollment
        self._enrolled_cards = enrolled_cards

    @property
    def control_rules(self):
        """
        Gets the control_rules of this BatchEnrollmentpostPayload.

        :return: The control_rules of this BatchEnrollmentpostPayload.
        :rtype: ControlRules
        """
        return self._control_rules

    @control_rules.setter
    def control_rules(self, control_rules):
        """
        Sets the control_rules of this BatchEnrollmentpostPayload.

        :param control_rules: The control_rules of this BatchEnrollmentpostPayload.
        :type: ControlRules
        """
        if control_rules is None:
            raise ValueError("Invalid value for `control_rules`, must not be `None`")

        self._control_rules = control_rules

    @property
    def cards_type(self):
        """
        Gets the cards_type of this BatchEnrollmentpostPayload.
        This represents whether the list of accountIdentifier is PAN or TOKEN.

        :return: The cards_type of this BatchEnrollmentpostPayload.
        :rtype: str
        """
        return self._cards_type

    @cards_type.setter
    def cards_type(self, cards_type):
        """
        Sets the cards_type of this BatchEnrollmentpostPayload.
        This represents whether the list of accountIdentifier is PAN or TOKEN.

        :param cards_type: The cards_type of this BatchEnrollmentpostPayload.
        :type: str
        """

        self._cards_type = cards_type

    @property
    def force_enrollment(self):
        """
        Gets the force_enrollment of this BatchEnrollmentpostPayload.
        If the indicator is set to true, previously enrolled accountIdentifier will be overwritten.

        :return: The force_enrollment of this BatchEnrollmentpostPayload.
        :rtype: bool
        """
        return self._force_enrollment

    @force_enrollment.setter
    def force_enrollment(self, force_enrollment):
        """
        Sets the force_enrollment of this BatchEnrollmentpostPayload.
        If the indicator is set to true, previously enrolled accountIdentifier will be overwritten.

        :param force_enrollment: The force_enrollment of this BatchEnrollmentpostPayload.
        :type: bool
        """

        self._force_enrollment = force_enrollment

    @property
    def enrolled_cards(self):
        """
        Gets the enrolled_cards of this BatchEnrollmentpostPayload.

        :return: The enrolled_cards of this BatchEnrollmentpostPayload.
        :rtype: EnrolledCards
        """
        return self._enrolled_cards

    @enrolled_cards.setter
    def enrolled_cards(self, enrolled_cards):
        """
        Sets the enrolled_cards of this BatchEnrollmentpostPayload.

        :param enrolled_cards: The enrolled_cards of this BatchEnrollmentpostPayload.
        :type: EnrolledCards
        """
        if enrolled_cards is None:
            raise ValueError("Invalid value for `enrolled_cards`, must not be `None`")

        self._enrolled_cards = enrolled_cards

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, BatchEnrollmentpostPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------