# coding: utf-8

"""
    Customer Rules API

    The Customer Rules API enables consumers to establish control rules that will define the type of transactions they want to Manage.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ManageControlspostPayload(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, global_controls=None, merchant_controls=None, transaction_controls=None):
        """
        ManageControlspostPayload - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'global_controls': 'GlobalControls',
            'merchant_controls': 'MerchantControls',
            'transaction_controls': 'TransactionControls'
        }

        self.attribute_map = {
            'global_controls': 'globalControls',
            'merchant_controls': 'merchantControls',
            'transaction_controls': 'transactionControls'
        }

        self._global_controls = global_controls
        self._merchant_controls = merchant_controls
        self._transaction_controls = transaction_controls

    @property
    def global_controls(self):
        """
        Gets the global_controls of this ManageControlspostPayload.

        :return: The global_controls of this ManageControlspostPayload.
        :rtype: GlobalControls
        """
        return self._global_controls

    @global_controls.setter
    def global_controls(self, global_controls):
        """
        Sets the global_controls of this ManageControlspostPayload.

        :param global_controls: The global_controls of this ManageControlspostPayload.
        :type: GlobalControls
        """

        self._global_controls = global_controls

    @property
    def merchant_controls(self):
        """
        Gets the merchant_controls of this ManageControlspostPayload.

        :return: The merchant_controls of this ManageControlspostPayload.
        :rtype: MerchantControls
        """
        return self._merchant_controls

    @merchant_controls.setter
    def merchant_controls(self, merchant_controls):
        """
        Sets the merchant_controls of this ManageControlspostPayload.

        :param merchant_controls: The merchant_controls of this ManageControlspostPayload.
        :type: MerchantControls
        """

        self._merchant_controls = merchant_controls

    @property
    def transaction_controls(self):
        """
        Gets the transaction_controls of this ManageControlspostPayload.

        :return: The transaction_controls of this ManageControlspostPayload.
        :rtype: TransactionControls
        """
        return self._transaction_controls

    @transaction_controls.setter
    def transaction_controls(self, transaction_controls):
        """
        Sets the transaction_controls of this ManageControlspostPayload.

        :param transaction_controls: The transaction_controls of this ManageControlspostPayload.
        :type: TransactionControls
        """

        self._transaction_controls = transaction_controls

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ManageControlspostPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------