# coding: utf-8

"""
    Customer Rules API

    The Customer Rules API enables consumers to establish control rules that will define the type of transactions they want to Manage.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UserInformation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, application_defined_attributes=None, banking_identifier=None, name=None):
        """
        UserInformation - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'application_defined_attributes': 'str',
            'banking_identifier': 'str',
            'name': 'str'
        }

        self.attribute_map = {
            'application_defined_attributes': 'applicationDefinedAttributes',
            'banking_identifier': 'bankingIdentifier',
            'name': 'name'
        }

        self._application_defined_attributes = application_defined_attributes
        self._banking_identifier = banking_identifier
        self._name = name

    @property
    def application_defined_attributes(self):
        """
        Gets the application_defined_attributes of this UserInformation.
        ApplicationDefinedAttributes by the issuer. These may be used to enrich the VTC notification alerts.

        :return: The application_defined_attributes of this UserInformation.
        :rtype: str
        """
        return self._application_defined_attributes

    @application_defined_attributes.setter
    def application_defined_attributes(self, application_defined_attributes):
        """
        Sets the application_defined_attributes of this UserInformation.
        ApplicationDefinedAttributes by the issuer. These may be used to enrich the VTC notification alerts.

        :param application_defined_attributes: The application_defined_attributes of this UserInformation.
        :type: str
        """

        self._application_defined_attributes = application_defined_attributes

    @property
    def banking_identifier(self):
        """
        Gets the banking_identifier of this UserInformation.
        Identifier for the issuer to map the user name

        :return: The banking_identifier of this UserInformation.
        :rtype: str
        """
        return self._banking_identifier

    @banking_identifier.setter
    def banking_identifier(self, banking_identifier):
        """
        Sets the banking_identifier of this UserInformation.
        Identifier for the issuer to map the user name

        :param banking_identifier: The banking_identifier of this UserInformation.
        :type: str
        """

        self._banking_identifier = banking_identifier

    @property
    def name(self):
        """
        Gets the name of this UserInformation.
        'name' of the user who configured the control.name is mandatory if UserInformation exists.

        :return: The name of this UserInformation.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this UserInformation.
        'name' of the user who configured the control.name is mandatory if UserInformation exists.

        :param name: The name of this UserInformation.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UserInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------