# coding: utf-8

"""
    Program Administration API

    The Transaction Controls Program Administration API enables Issuers to change program configurations for their sponsorID.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CardEnrollmentCallbackSettings(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, iscall_back_endpoint_local=None, call_back_endpoint=None, is_call_back_disabled=None):
        """
        CardEnrollmentCallbackSettings - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'iscall_back_endpoint_local': 'bool',
            'call_back_endpoint': 'str',
            'is_call_back_disabled': 'bool'
        }

        self.attribute_map = {
            'iscall_back_endpoint_local': 'iscallBackEndpointLocal',
            'call_back_endpoint': 'callBackEndpoint',
            'is_call_back_disabled': 'isCallBackDisabled'
        }

        self._iscall_back_endpoint_local = iscall_back_endpoint_local
        self._call_back_endpoint = call_back_endpoint
        self._is_call_back_disabled = is_call_back_disabled

    @property
    def iscall_back_endpoint_local(self):
        """
        Gets the iscall_back_endpoint_local of this CardEnrollmentCallbackSettings.
        This value indicates whether callback URL is on a local network, Default is false will be send via WSI

        :return: The iscall_back_endpoint_local of this CardEnrollmentCallbackSettings.
        :rtype: bool
        """
        return self._iscall_back_endpoint_local

    @iscall_back_endpoint_local.setter
    def iscall_back_endpoint_local(self, iscall_back_endpoint_local):
        """
        Sets the iscall_back_endpoint_local of this CardEnrollmentCallbackSettings.
        This value indicates whether callback URL is on a local network, Default is false will be send via WSI

        :param iscall_back_endpoint_local: The iscall_back_endpoint_local of this CardEnrollmentCallbackSettings.
        :type: bool
        """

        self._iscall_back_endpoint_local = iscall_back_endpoint_local

    @property
    def call_back_endpoint(self):
        """
        Gets the call_back_endpoint of this CardEnrollmentCallbackSettings.
        The alert notification callback URL, must be minimum 6, maximum of 150 charcters long

        :return: The call_back_endpoint of this CardEnrollmentCallbackSettings.
        :rtype: str
        """
        return self._call_back_endpoint

    @call_back_endpoint.setter
    def call_back_endpoint(self, call_back_endpoint):
        """
        Sets the call_back_endpoint of this CardEnrollmentCallbackSettings.
        The alert notification callback URL, must be minimum 6, maximum of 150 charcters long

        :param call_back_endpoint: The call_back_endpoint of this CardEnrollmentCallbackSettings.
        :type: str
        """
        if call_back_endpoint is None:
            raise ValueError("Invalid value for `call_back_endpoint`, must not be `None`")

        self._call_back_endpoint = call_back_endpoint

    @property
    def is_call_back_disabled(self):
        """
        Gets the is_call_back_disabled of this CardEnrollmentCallbackSettings.
        This value indicates whether callback is turned on(false), or off(true)

        :return: The is_call_back_disabled of this CardEnrollmentCallbackSettings.
        :rtype: bool
        """
        return self._is_call_back_disabled

    @is_call_back_disabled.setter
    def is_call_back_disabled(self, is_call_back_disabled):
        """
        Sets the is_call_back_disabled of this CardEnrollmentCallbackSettings.
        This value indicates whether callback is turned on(false), or off(true)

        :param is_call_back_disabled: The is_call_back_disabled of this CardEnrollmentCallbackSettings.
        :type: bool
        """
        if is_call_back_disabled is None:
            raise ValueError("Invalid value for `is_call_back_disabled`, must not be `None`")

        self._is_call_back_disabled = is_call_back_disabled

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CardEnrollmentCallbackSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------