# coding: utf-8

"""
    Alert History and Customer Profiles API

    The Alert History and Customer Profiles API is used to retrieve alert history information and for issuers using the VTC Alert Delivery Service to store cardholder contact information.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .alert_preferences import AlertPreferences
from .alert_preferences_inner import AlertPreferencesInner
from .alerts_preferences import AlertsPreferences
from .collection_resource_of_customer_profile_document import CollectionResourceOfCustomerProfileDocument
from .contacts import Contacts
from .contacts_inner import ContactsInner
from .create_customer_alert_profilepost_payload import CreateCustomerAlertProfilepostPayload
from .create_customer_alert_profilepost_response import CreateCustomerAlertProfilepostResponse
from .customer_alerts_profileget_response import CustomerAlertsProfilegetResponse
from .customer_alerts_profilepatch_payload import CustomerAlertsProfilepatchPayload
from .customer_alerts_profilepatch_response import CustomerAlertsProfilepatchResponse
from .customer_profile_document import CustomerProfileDocument
from .default_alerts_preferences import DefaultAlertsPreferences
from .get_notification_detailsget_response import GetNotificationDetailsgetResponse
from .get_notifications_summary_by_pan_or_tokenpost_payload import GetNotificationsSummaryByPanOrTokenpostPayload
from .get_notifications_summary_by_pan_or_tokenpost_response import GetNotificationsSummaryByPanOrTokenpostResponse
from .manage_alerts_preferencesdelete_payload import ManageAlertsPreferencesdeletePayload
from .manage_alerts_preferencesdelete_response import ManageAlertsPreferencesdeleteResponse
from .manage_alerts_preferencespost_payload import ManageAlertsPreferencespostPayload
from .manage_alerts_preferencespost_response import ManageAlertsPreferencespostResponse
from .manage_alerts_preferencesput_payload import ManageAlertsPreferencesputPayload
from .manage_alerts_preferencesput_response import ManageAlertsPreferencesputResponse
from .pagination import Pagination
from .resource import Resource
from .time_range import TimeRange

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------