# Generated by Django 3.0.5 on 2024-03-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.IntegerField()),
                ('Applicant', models.CharField(max_length=255)),
                ('FacilityType', models.CharField(max_length=100)),
                ('cnn', models.IntegerField()),
                ('LocationDescription', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('blocklot', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('lot', models.CharField(max_length=255)),
                ('permit', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('FoodItems', models.TextField()),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Schedule', models.CharField(max_length=255)),
                ('dayshours', models.CharField(max_length=255)),
                ('NOISent', models.IntegerField()),
                ('Approved', models.CharField(max_length=100)),
                ('Received', models.CharField(max_length=100)),
                ('PriorPermit', models.CharField(max_length=100)),
                ('ExpirationDate', models.DateField()),
                ('Location', models.CharField(max_length=255)),
                ('FirePreventionDistricts', models.IntegerField()),
                ('PoliceDistricts', models.IntegerField()),
                ('SupervisorDistricts', models.IntegerField()),
                ('ZipCodes', models.IntegerField()),
                ('Neighborhoods', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
