# Generated by Django 3.0.5 on 2024-03-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0003_auto_20240306_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodvendor',
            name='X',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='foodvendor',
            name='Y',
            field=models.FloatField(blank=True),
        ),
    ]
