version: '3.8'
services:
  luffy:
    build: .
    container_name: luffy-container
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - my-network
    volumes:
      - .:/app
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - '27017:27017'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
