# coding: utf-8

"""
    Program Administration API

    The Transaction Controls Program Administration API enables Issuers to change program configurations for their sponsorID.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re
import json

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class ProgAdminApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()

        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def deletemanage_rule_configuration(self, manage_rule_configurationdelete_payload, **kwargs):
        """
        Delete the consumer transaction controls that the issuer has made avaiable to its cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.deletemanage_rule_configuration(manage_rule_configurationdelete_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageRuleConfigurationdeletePayload manage_rule_configurationdelete_payload: request (required)
        :return: ManageRuleConfigurationdeleteResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.deletemanage_rule_configuration_with_http_info(manage_rule_configurationdelete_payload, **kwargs)
        else:
            (data) = self.deletemanage_rule_configuration_with_http_info(manage_rule_configurationdelete_payload, **kwargs)
            return data

    def deletemanage_rule_configuration_with_http_info(self, manage_rule_configurationdelete_payload, **kwargs):
        """
        Delete the consumer transaction controls that the issuer has made avaiable to its cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.deletemanage_rule_configuration_with_http_info(manage_rule_configurationdelete_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageRuleConfigurationdeletePayload manage_rule_configurationdelete_payload: request (required)
        :return: ManageRuleConfigurationdeleteResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['manage_rule_configurationdelete_payload']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method deletemanage_rule_configuration" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'manage_rule_configurationdelete_payload' is set
        if ('manage_rule_configurationdelete_payload' not in params) or (params['manage_rule_configurationdelete_payload'] is None):
            raise ValueError("Missing the required parameter `manage_rule_configurationdelete_payload` when calling `deletemanage_rule_configuration`")


        collection_formats = {}

        path = '/vctc/programadmin//v1/sponsors/configuration'.replace('{format}', 'json')
        resource_path = 'sponsors/configuration'
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'manage_rule_configurationdelete_payload' in params:
            body_params = params['manage_rule_configurationdelete_payload']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['basicAuth']

        return self.api_client.call_api(path, resource_path, 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ManageRuleConfigurationdeleteResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def deletemanage_transaction_controls(self, manage_transaction_controlsdelete_payload, **kwargs):
        """
        Delete transaction type controls that the issuer has made available to its cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.deletemanage_transaction_controls(manage_transaction_controlsdelete_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageTransactionControlsdeletePayload manage_transaction_controlsdelete_payload: request (required)
        :return: ManageTransactionControlsdeleteResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.deletemanage_transaction_controls_with_http_info(manage_transaction_controlsdelete_payload, **kwargs)
        else:
            (data) = self.deletemanage_transaction_controls_with_http_info(manage_transaction_controlsdelete_payload, **kwargs)
            return data

    def deletemanage_transaction_controls_with_http_info(self, manage_transaction_controlsdelete_payload, **kwargs):
        """
        Delete transaction type controls that the issuer has made available to its cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.deletemanage_transaction_controls_with_http_info(manage_transaction_controlsdelete_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageTransactionControlsdeletePayload manage_transaction_controlsdelete_payload: request (required)
        :return: ManageTransactionControlsdeleteResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['manage_transaction_controlsdelete_payload']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method deletemanage_transaction_controls" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'manage_transaction_controlsdelete_payload' is set
        if ('manage_transaction_controlsdelete_payload' not in params) or (params['manage_transaction_controlsdelete_payload'] is None):
            raise ValueError("Missing the required parameter `manage_transaction_controlsdelete_payload` when calling `deletemanage_transaction_controls`")


        collection_formats = {}

        path = '/vctc/programadmin//v1/configuration/transactiontypecontrols'.replace('{format}', 'json')
        resource_path = 'configuration/transactiontypecontrols'
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'manage_transaction_controlsdelete_payload' in params:
            body_params = params['manage_transaction_controlsdelete_payload']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['basicAuth']

        return self.api_client.call_api(path, resource_path, 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ManageTransactionControlsdeleteResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def getmanage_rule_configuration(self, **kwargs):
        """
        Retrieve list of rule categories that issuer has made available to its cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.getmanage_rule_configuration(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :return: ManageRuleConfigurationgetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.getmanage_rule_configuration_with_http_info(**kwargs)
        else:
            (data) = self.getmanage_rule_configuration_with_http_info(**kwargs)
            return data

    def getmanage_rule_configuration_with_http_info(self, **kwargs):
        """
        Retrieve list of rule categories that issuer has made available to its cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.getmanage_rule_configuration_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :return: ManageRuleConfigurationgetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method getmanage_rule_configuration" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path = '/vctc/programadmin//v1/sponsors/configuration'.replace('{format}', 'json')
        resource_path = 'sponsors/configuration'
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['basicAuth']

        return self.api_client.call_api(path, resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ManageRuleConfigurationgetResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def getmanage_transaction_controls(self, **kwargs):
        """
        Retrieve the list of transaction type controls that the issuer has made available to its cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.getmanage_transaction_controls(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :return: ManageTransactionControlsgetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.getmanage_transaction_controls_with_http_info(**kwargs)
        else:
            (data) = self.getmanage_transaction_controls_with_http_info(**kwargs)
            return data

    def getmanage_transaction_controls_with_http_info(self, **kwargs):
        """
        Retrieve the list of transaction type controls that the issuer has made available to its cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.getmanage_transaction_controls_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :return: ManageTransactionControlsgetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method getmanage_transaction_controls" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path = '/vctc/programadmin//v1/configuration/transactiontypecontrols'.replace('{format}', 'json')
        resource_path = 'configuration/transactiontypecontrols'
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['basicAuth']

        return self.api_client.call_api(path, resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ManageTransactionControlsgetResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def postmanage_rule_configuration(self, manage_rule_configurationpost_payload, **kwargs):
        """
        Add new rule categories for use by issuer's cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.postmanage_rule_configuration(manage_rule_configurationpost_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageRuleConfigurationpostPayload manage_rule_configurationpost_payload: request (required)
        :return: ManageRuleConfigurationpostResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.postmanage_rule_configuration_with_http_info(manage_rule_configurationpost_payload, **kwargs)
        else:
            (data) = self.postmanage_rule_configuration_with_http_info(manage_rule_configurationpost_payload, **kwargs)
            return data

    def postmanage_rule_configuration_with_http_info(self, manage_rule_configurationpost_payload, **kwargs):
        """
        Add new rule categories for use by issuer's cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.postmanage_rule_configuration_with_http_info(manage_rule_configurationpost_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageRuleConfigurationpostPayload manage_rule_configurationpost_payload: request (required)
        :return: ManageRuleConfigurationpostResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['manage_rule_configurationpost_payload']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method postmanage_rule_configuration" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'manage_rule_configurationpost_payload' is set
        if ('manage_rule_configurationpost_payload' not in params) or (params['manage_rule_configurationpost_payload'] is None):
            raise ValueError("Missing the required parameter `manage_rule_configurationpost_payload` when calling `postmanage_rule_configuration`")


        collection_formats = {}

        path = '/vctc/programadmin//v1/sponsors/configuration'.replace('{format}', 'json')
        resource_path = 'sponsors/configuration'
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'manage_rule_configurationpost_payload' in params:
            body_params = params['manage_rule_configurationpost_payload']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['basicAuth']

        return self.api_client.call_api(path, resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ManageRuleConfigurationpostResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def postmanage_transaction_controls(self, manage_transaction_controlspost_payload, **kwargs):
        """
        Add new transaction type controls for the issuer's cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.postmanage_transaction_controls(manage_transaction_controlspost_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageTransactionControlspostPayload manage_transaction_controlspost_payload: request (required)
        :return: ManageTransactionControlspostResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.postmanage_transaction_controls_with_http_info(manage_transaction_controlspost_payload, **kwargs)
        else:
            (data) = self.postmanage_transaction_controls_with_http_info(manage_transaction_controlspost_payload, **kwargs)
            return data

    def postmanage_transaction_controls_with_http_info(self, manage_transaction_controlspost_payload, **kwargs):
        """
        Add new transaction type controls for the issuer's cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.postmanage_transaction_controls_with_http_info(manage_transaction_controlspost_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageTransactionControlspostPayload manage_transaction_controlspost_payload: request (required)
        :return: ManageTransactionControlspostResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['manage_transaction_controlspost_payload']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method postmanage_transaction_controls" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'manage_transaction_controlspost_payload' is set
        if ('manage_transaction_controlspost_payload' not in params) or (params['manage_transaction_controlspost_payload'] is None):
            raise ValueError("Missing the required parameter `manage_transaction_controlspost_payload` when calling `postmanage_transaction_controls`")


        collection_formats = {}

        path = '/vctc/programadmin//v1/configuration/transactiontypecontrols'.replace('{format}', 'json')
        resource_path = 'configuration/transactiontypecontrols'
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'manage_transaction_controlspost_payload' in params:
            body_params = params['manage_transaction_controlspost_payload']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['basicAuth']

        return self.api_client.call_api(path, resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ManageTransactionControlspostResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def putmanage_rule_configuration(self, manage_rule_configurationput_payload, **kwargs):
        """
        Update existing set of rule categories with a new set for use by issuer's cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.putmanage_rule_configuration(manage_rule_configurationput_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageRuleConfigurationputPayload manage_rule_configurationput_payload: request (required)
        :return: ManageRuleConfigurationputResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.putmanage_rule_configuration_with_http_info(manage_rule_configurationput_payload, **kwargs)
        else:
            (data) = self.putmanage_rule_configuration_with_http_info(manage_rule_configurationput_payload, **kwargs)
            return data

    def putmanage_rule_configuration_with_http_info(self, manage_rule_configurationput_payload, **kwargs):
        """
        Update existing set of rule categories with a new set for use by issuer's cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.putmanage_rule_configuration_with_http_info(manage_rule_configurationput_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageRuleConfigurationputPayload manage_rule_configurationput_payload: request (required)
        :return: ManageRuleConfigurationputResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['manage_rule_configurationput_payload']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method putmanage_rule_configuration" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'manage_rule_configurationput_payload' is set
        if ('manage_rule_configurationput_payload' not in params) or (params['manage_rule_configurationput_payload'] is None):
            raise ValueError("Missing the required parameter `manage_rule_configurationput_payload` when calling `putmanage_rule_configuration`")


        collection_formats = {}

        path = '/vctc/programadmin//v1/sponsors/configuration'.replace('{format}', 'json')
        resource_path = 'sponsors/configuration'
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'manage_rule_configurationput_payload' in params:
            body_params = params['manage_rule_configurationput_payload']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['basicAuth']

        return self.api_client.call_api(path, resource_path, 'PUT',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ManageRuleConfigurationputResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def putmanage_transaction_controls(self, manage_transaction_controlsput_payload, **kwargs):
        """
        Update existing set of transaction type controls with a new set for the issuer's cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.putmanage_transaction_controls(manage_transaction_controlsput_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageTransactionControlsputPayload manage_transaction_controlsput_payload: request (required)
        :return: ManageTransactionControlsputResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.putmanage_transaction_controls_with_http_info(manage_transaction_controlsput_payload, **kwargs)
        else:
            (data) = self.putmanage_transaction_controls_with_http_info(manage_transaction_controlsput_payload, **kwargs)
            return data

    def putmanage_transaction_controls_with_http_info(self, manage_transaction_controlsput_payload, **kwargs):
        """
        Update existing set of transaction type controls with a new set for the issuer's cardholders
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.putmanage_transaction_controls_with_http_info(manage_transaction_controlsput_payload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param ManageTransactionControlsputPayload manage_transaction_controlsput_payload: request (required)
        :return: ManageTransactionControlsputResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['manage_transaction_controlsput_payload']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method putmanage_transaction_controls" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'manage_transaction_controlsput_payload' is set
        if ('manage_transaction_controlsput_payload' not in params) or (params['manage_transaction_controlsput_payload'] is None):
            raise ValueError("Missing the required parameter `manage_transaction_controlsput_payload` when calling `putmanage_transaction_controls`")


        collection_formats = {}

        path = '/vctc/programadmin//v1/configuration/transactiontypecontrols'.replace('{format}', 'json')
        resource_path = 'configuration/transactiontypecontrols'
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'manage_transaction_controlsput_payload' in params:
            body_params = params['manage_transaction_controlsput_payload']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['basicAuth']

        return self.api_client.call_api(path, resource_path, 'PUT',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ManageTransactionControlsputResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------