version: '3'

services:
  backend:
    build:
      context: ./backend/zoro
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/zoro:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app

